### ISSUE TITLE
test 1

### ISSUE THREAD

**Issue by krammer0** [surveyTW/themes-survey#1]

**Comment by asdkda** [comment]
Issue list here!!  Sounds good.

**Comment by krammer0** [comment]
I'm trying to find how to use label....

**Comment by asdkda** [comment]
**Like this ?**

**Comment by krammer0** [comment]
yeah, how? hahah

**Comment by asdkda** [comment]
Just on the right side bar next to comment list.  Labels, Milestone, Assignee...
