### ISSUE TITLE
沒登入不該能進入"馬上約"

### ISSUE THREAD

**Issue by krammer0** [surveyTW/themes-survey#10]

**Comment by krammer0** [comment]
我試著改掉surveydate的access權限 現在變成這樣
![2015-01-22 11 11 21](https://cloud.githubusercontent.com/assets/9051392/5858148/ffb83d64-a28b-11e4-897f-2ed3de8df096.png)

**Comment by JohnnyMayson** [comment]
問一下 最上面的menu你怎麼把馬上約拿掉的

**Comment by krammer0** [comment]
咦 我沒注意到那個不見了 我主要是去改surveydate的權限 改成ANONYMOUS USER不能access 但理論上應該是要改成沒登入的按下去會跳轉到註冊/登入的那頁才對XD

**Comment by JohnnyMayson** [comment]
應該是沒權限的PAGE就不會秀在MENU上了 了解了 我以為是改CODE的方式所以問一下

**Comment by krammer0** [comment]
喔喔 ok!
