### ISSUE TITLE
改密碼的頁面 邊改密碼顏色還是不會變

### ISSUE THREAD

**Issue by krammer0** [surveyTW/themes-survey#11]

**Comment by duntsao** [comment]
這issue用root登入不會有耶.!!!...是權限設定嗎?

**Comment by duntsao** [comment]
Root跟一般使用者用的版型不一樣...是不是這造成的啊?

**Comment by asdkda** [comment]
root 預設版型是 seven, 換成 bootstrap 之後會有一樣的情形

要修改 root 版型可以參考下圖標示

![screenshot-54 199 171 173 2015-02-04 23-30-48](https://cloud.githubusercontent.com/assets/4745434/6043279/2cc5017c-acc6-11e4-81eb-8a29584ba704.png)

**Comment by krammer0** [comment]
用最新的bootstrap就解了
