### ISSUE TITLE
首頁的選單 for Johnny

### ISSUE THREAD

**Issue by duntsao** [surveyTW/themes-survey#18]
Johnny首頁的選單有
1. 馬上約
2. 人氣意見票選
3. 聯絡我們

第一版目前就這三個...

**Comment by JohnnyMayson** [comment]
2 3項都要給連結

**Comment by krammer0** [comment]
還有註冊/登入的連結 然後已登入的話是不是就要把這連結變成登出@@?

**Comment by asdkda** [comment]
登入登出連結 Johnny 應該知道就不給了
臉書登入請用 user/simple-fb-connect

**Comment by duntsao** [comment]
Johnny... 2,3項我們還沒有弄好...第三項你那邊有temple嗎?...只需要名字...e-mail,...跟意見回覆欄位就可以了...寄信的功能我之後再加上去...

**Comment by duntsao** [comment]
我弄好一版google form...大家review 一下...
https://docs.google.com/forms/d/1NVfZdsFQktEWcjaYncs7FjfHZwSZqyLLPtL6lV_MdMs/viewform

Johnny下面是這個google form砍入的code...

<iframe src="https://docs.google.com/forms/d/1NVfZdsFQktEWcjaYncs7FjfHZwSZqyLLPtL6lV_MdMs/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">載入中…</iframe>

**Comment by JohnnyMayson** [comment]
未登入會出現登入選項 登入以後會隱藏登入選項

**Comment by JohnnyMayson** [comment]
聯絡我們這個呢
