### ISSUE TITLE
survey date view有時候打開google map會有錯誤

### ISSUE THREAD

**Issue by JohnnyMayson** [surveyTW/themes-survey#21]
![image](https://cloud.githubusercontent.com/assets/8788866/5890958/7ee100c6-a4b2-11e4-85f7-ff576d5a298b.png)

Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by JohnnyMayson** [comment]
建立survey date也會!!!!

**Comment by duntsao** [comment]
鈞達apply Google API key

**Comment by asdkda** [comment]
The Google Map API key has been applied.
