### ISSUE TITLE
語言包issue

### ISSUE THREAD

**Issue by duntsao** [surveyTW/themes-survey#41]
Enable 中文...Calendar不能選取...

**Comment by JohnnyMayson** [comment]
http://huli.logdown.com/posts/211220-jquery-plugin-multi-language

**Comment by JohnnyMayson** [comment]
語言包
http://ithelp.ithome.com.tw/question/10120587

詳細語言包教學
http://yhhuang1966.blogspot.tw/2013/04/jquery-ui-datepicker.html

Multiple-Dates-Picker語言解法
https://github.com/dubrox/Multiple-Dates-Picker-for-jQuery-UI/issues/61

直接設定date格式不用語言
http://stackoverflow.com/questions/9773746/how-to-fix-regional-settings-for-jquery-datepicker-so-it-works-in-firefox-and-ie
