### ISSUE TITLE
地點選紐約文創的時候 存完show出會變到台中

### ISSUE THREAD

**Issue by krammer0** [surveyTW/themes-survey#6]

**Comment by JohnnyMayson** [comment]
主要是GOOGLE MAP的問題

解法一 : 一開始就要給地圖一個定位點 然後在作找地址的動作 例如一開始定位使用者位置作定位點 但是使用者在國外一樣GG

解法二 : 在建立表單 存入地址的時候就要有location的經緯度

**Comment by duntsao** [comment]
Google Map改存座標資料....

**Comment by asdkda** [comment]
新增新的欄位 latlng 來存放座標, 並改用座標來顯示地圖
